# Utiliza una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo en la carpeta de la aplicación
WORKDIR /app

# Copia el archivo `package.json` y `package-lock.json` para instalar las dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todos los archivos del directorio actual al directorio de trabajo en el contenedor
COPY . .

# Compila la aplicación de React
RUN npm run build

# Expone el puerto 3000 (el puerto en el que generalmente se ejecuta una aplicación de React)
EXPOSE 3000

# Comando para iniciar la aplicación cuando el contenedor se inicie
CMD ["npm", "start"]

#sudo docker build -t juanpablogc/frontend-sopes1-proyecto1 .
#sudo docker run -it --rm  -p 3000:3000 juanpablogc/frontend-sopes1-proyecto1

#sudo docker tag juanpablogc/frontend-sopes1-proyecto1:latest juanpablogc/so1_proyecto1:frontend-sopes1-proyecto1
#sudo docker push juanpablogc/so1_proyecto1:frontend-sopes1-proyecto1