# Establecer la imagen base
FROM node:14-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo package.json y el archivo package-lock.json (si existe)
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el código fuente del backend
COPY . .

# Exponer el puerto en el que se ejecuta la aplicación Node.js
EXPOSE 4000

# Comando para iniciar el servidor Node.js
CMD ["node", "server.js"]

